---
- name: Install Tomcat Server in Ubuntu 20.04
  become: yes
  hosts: all
  vars:
    java_package_name: openjdk-11-jdk
    tomcat_user: tomcat
    tomcat_home_dirctory: /opt/tomcat
    user_bin: /bin/false
    tomcat_url: https://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
    tomcat_download_destination: /tmp/apache-tomcat-9.0.65.tar.gz
    tomcat_service_file_location: tomcat.service
    tomcat_service_file_destination: /etc/systemd/system/tomcat.service
  tasks: 
    - name: install java openjdk-11-jdk
      ansible.builtin.apt:
        name: '{{ java_package_name}}'
        state: present
        update_cache: yes
    - name: Creating tomcat user and home directory
      ansible.builtin.user:
        name: '{{ tomcat_user }}'
        create_home: yes
        shell: '{{ user_bin }}'
        home: '{{tomcat_home_dirctory}}'
    - name: Download tomcat package
      ansible.builtin.get_url:
        url: '{{tomcat_url}}'
        dest: '{{tomcat_download_destination}}'
    - name: Extracting tomcat 
      ansible.builtin.unarchive:
        src: '{{ tomcat_download_destination}}'
        dest: '{{tomcat_home_dirctory}}'
        remote_src: yes
    - name: Creating symbolic link
      ansible.builtin.file:
        src: '{{tomcat_home_dirctory}}/apache-tomcat-9.0.65'
        dest: '{{ tomcat_home_dirctory}}/latest'
        owner: '{{ tomcat_user }}'
        group: '{{ tomcat_user }}'
        state: link
    - name: Changing ownership to user
      ansible.builtin.file:
        path: '{{ tomcat_home_dirctory }}'
        owner: '{{ tomcat_user}}'
        group: '{{tomcat_user}}'
        state: directory
        recurse: yes
    - name: Give Execute permissions to shell files in tomcat's bin directory
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "+x"
      with_fileglob:
        - "{{ tomcat_home_dirctory }}/latest/bin/*.sh"
    - name: Copying tomcat.service file to the remote system
      ansible.builtin.copy:
        src: '{{ tomcat_service_file_location}}'
        dest: '{{ tomcat_service_file_destination}}'
    - name: Restart Deamon reload
      ansible.builtin.systemd:
        state: restarted
        name: tomcat
        daemon_reload: yes
        enabled: yes