---
- name: Install tomcat 9 in Ubuntu
  become: yes
  hosts: all
  tasks:
    - debug:
        msg: "This playbook supports only on Centos and Ubuntu"
    - name: Terminated Execution due to Unsuppoprted OS for Playbook
      ansible.builtin.fail:
        msg: Failed due to unsupported OS
      when: 
        - ansible_facts['distribution'] != "CentoS"
        - ansible_facts['distribution'] != "Ubuntu"
    - name: update the software and installing "{{ java_package_name }}"
      ansible.builtin.package:
        name: "{{ java_package_name }}"
        update_cache: yes
        state: present
    - debug: 
        msg: "installing {{ java_package_name }}"
    - name: Add the user 'tomcat' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: '{{tomcat_user}}'
        create_home: yes
        home: '{{tomcat_home_path}}'
        shell: "{{ tomcat_shell }}"
    - debug:
        msg: "creating an user {{ tomcat_user }} with home directory {{ tomcat_home_path }} ans shell {{ tomcat_shell }}"
    - debug:
        msg: "Downloading Tomcat Server from {{ tomcat_url }}"
    - name: Download tomcat server
      ansible.builtin.get_url:
        url: '{{ tomcat_url }}'
        dest: '{{ tomcat_download_location }}'
      notify:
      - Extracting the tomcat
    - debug:
        msg: "Extracting Tomcat to {{ tomcat_home_path }}"
    - name: Creating symbolic link
      ansible.builtin.file:
        src: '{{tomcat_home_path}}/apache-tomcat-9.0.65'
        dest: '{{ tomcat_home_path}}/latest'
        owner: '{{ tomcat_user }}'
        group: '{{ tomcat_user }}'
        state: link
    - debug:
        msg: "Created Symbolic Link"
    - name: Changing the ownership of tomcat directory
      ansible.builtin.file:
        path: '{{ tomcat_home_path}}'
        owner: '{{ tomcat_user }}'
        recurse: yes
        group: '{{ tomcat_user }}'
        state: directory
    - debug:
        msg: "Ownership of tomcat directory changed to {{ tomcat_user }}"
    - name: Give Execute permissions to shell files in tomcat's bin directory
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "+x"
      with_fileglob:
        - "{{ tomcat_home_path }}/latest/bin/*.sh"
    - debug:
        msg: "Copying tomcat.service file"
    - name: Copy a "tomcat.service" file  to the node
      ansible.builtin.copy:
        src: tomcat.service.j2
        dest: "{{ tomcat_service_file_location }}"
    - name: Copy tomcat users file
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: "{{ tomcat_user_file_location }}"
    - name: Copy tomcat users file
      ansible.builtin.copy:
        src: manager-file.xml
        dest: "{{ tomcat_manager_app_file_location }}"
    - name: Copy tomcat users file
      ansible.builtin.copy:
        src: hostmanager-file.xml
        dest: "{{ tomcat_hostmanager_app_file_location }}"
      notify: 
        - reload daemon
  handlers:
    - name: reload daemon
      ansible.builtin.systemd:
        name: tomcat
        daemon_reload: yes
        enabled: yes
        state: started
    - name: Extracting the tomcat
      ansible.builtin.unarchive:
        src: '{{ tomcat_download_location }}'
        dest: '{{ tomcat_home_path }}'
        remote_src: yes